### ISSUE TITLE
THW Import mixes up organizations

### ISSUE THREAD

**Issue by KrugT** [HelfenKannJeder/helf-o-mat#228]
Importing the current dataset from thw.de results in data from THW Berlin Steglitz-Zehlendorf being applied to Berlin Tempelhof-Schöneberg and vice versa.

This is likely caused by the duplicate prevention mechanism. The address of both organizations are almost identical. "Gallwitzallee 123-143" vs "Gallwitzallee 123-143 Haus 13"

**Comment by KrugT** [comment]
Should we have introduce some configuraiton to resolve having multiple organizaitons of the same type at the same location?

**Comment by vzickner** [comment]
We are using Google Maps to get the coordinates based on the address. Maybe the result of the address is for both the same and it takes the wrong item from the list?
