### ISSUE TITLE
OrganizationEditDeleteContactPersonEvent not applied correctly

### ISSUE THREAD

**Issue by KrugT** [HelfenKannJeder/helf-o-mat#233]
When a contract person was removed and a new one added, there seem to be two correct events visible in the review.
Once the change is approved, both contact person are still visible for the organization.

Example: THW Bitburg from 01/08/21.
The example changes where reread by the import application.

**Comment by vzickner** [comment]
The importer removed the contact person with a wrong phone number. That's the reason why the event got ignored.

**Comment by vzickner** [comment]
I added a warning in case an event doesn't match. This kind of events are disabled by default and can't be enabled.
